[package]
name = "peek"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"

fuzzy-matcher = "0.3"
crossterm = "0.27"
ratatui = "0.27"
anyhow = "1.0"
env_logger = "0.11"
log = "0.4"
dirs = "5.0"
